# Generated by Django 4.2.4 on 2023-08-02 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 2, 11, 54, 59, 404834))),
                ('search_text', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
