# Generated by Django 4.2.4 on 2023-08-02 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trackedproducts_alter_productresult_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresult',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 13, 20, 48, 791819)),
        ),
        migrations.AlterField(
            model_name='trackedproducts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 13, 20, 48, 792649)),
        ),
    ]
