# Generated by Django 4.2.4 on 2023-08-02 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_productresult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trackedproducts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
